services:
  - type: web
    name: gesture-ease-backend
    runtime: docker
    region: oregon
    plan: free
    rootDir: backend
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "1"
    autoDeploy: true

  - type: web
    name: gesture-ease-frontend
    runtime: docker
    region: oregon
    plan: free
    rootDir: frontend
    dockerfilePath: frontend/Dockerfile
    envVars:
      - key: REACT_APP_BACKEND_URL
        fromService:
          name: gesture-ease-backend
          property: url
    autoDeploy: true
